### ISSUE TITLE
Wrong FileTime

### ISSUE THREAD

**Issue by ed-so** [anderbggo/GooglePhotosMatcher#1]
Photos have wrong date.
In json file there are 2 different dates.
creationTime and photoTakenTime.
in my case photoTakenTime would be the correct time

**Comment by anderbggo** [comment]
Hi! I will check it

**Comment by daniaalnadir** [comment]
Yup just saw the same. Line 55, main.py
`timeStamp = int(data['creationTime']['timestamp']) # Get creation time` wants to be 
`timeStamp = int(data['photoTakenTime']['timestamp']) # Get creation time`

**Comment by anderbggo** [comment]
> Yup just saw the same. Line 55, main.py
> `timeStamp = int(data['creationTime']['timestamp']) # Get creation time` wants to be 
> `timeStamp = int(data['photoTakenTime']['timestamp']) # Get creation time` 
> 

In my case both attributes had the same date. I will change it for this week for sure!
