### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by shlomis1** [anderbggo/GooglePhotosMatcher#4]
It's working on most folders but on a few, it fails with the below exception:
![image](https://user-images.githubusercontent.com/3199263/217728852-2e0f0564-b8b0-48b0-b6c0-3e1a89ac6470.png)

**Comment by anderbggo** [comment]
It seems that the source of the problem is a program which is using the same resource at the same time. I recommend you to reboot and do not open anything except the executable.

If the issue persists, open it again

^^
