### ISSUE TITLE
Image Files Deleted

### ISSUE THREAD

**Issue by CyberstormFox** [anderbggo/GooglePhotosMatcher#6]
I ran this tool on a simple 5 image album, and the result state 3 successful and 1 error. In addition to not seeing where this error is, and more importantly, the resulting output was that 2 of the images were simply deleted. The are no longer in the folder the originally were, nor the resulting created "MatchedMedia" or "EditedRaw" folders.  All images were JPG and had appropriately matching json files with no typos or odd characters in their names

**Comment by anderbggo** [comment]
Hi, can you give the names of the jpgs? 

Thank you
